export const PERMISSIONS = {
  USERS_READ: 'users.read', USERS_CREATE: 'users.create', USERS_UPDATE: 'users.update', USERS_DELETE: 'users.delete', SYSTEM_MANAGE: 'system.manage', AUDIT_READ: 'audit.read',
  FACULTY_READ: 'faculty.read', FACULTY_CREATE: 'faculty.create', FACULTY_UPDATE: 'faculty.update', FACULTY_DELETE: 'faculty.delete',
  DEPARTMENT_READ: 'department.read', DEPARTMENT_CREATE: 'department.create', DEPARTMENT_UPDATE: 'department.update', DEPARTMENT_DELETE: 'department.delete',
  PROGRAM_READ: 'program.read', PROGRAM_CREATE: 'program.create', PROGRAM_UPDATE: 'program.update', PROGRAM_DELETE: 'program.delete',
  COURSE_READ: 'course.read', COURSE_CREATE: 'course.create', COURSE_UPDATE: 'course.update', COURSE_DELETE: 'course.delete',
  STUDENTS_READ: 'students.read', STUDENTS_CREATE: 'students.create', STUDENTS_UPDATE: 'students.update', STUDENTS_MANAGE: 'students.manage',
  LECTURERS_READ: 'lecturers.read', LECTURERS_CREATE: 'lecturers.create', LECTURERS_UPDATE: 'lecturers.update', LECTURERS_MANAGE: 'lecturers.manage',
  ACADEMIC_YEAR_MANAGE: 'academic_year.manage', SEMESTER_MANAGE: 'semester.manage', COURSE_SECTION_MANAGE: 'course_section.manage',
  REGISTRATION_READ: 'registration.read', REGISTRATION_CREATE: 'registration.create', REGISTRATION_APPROVE: 'registration.approve', REGISTRATION_REJECT: 'registration.reject',

  // Phase 3 Permissions
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_CREATE: 'attendance.create',
  ATTENDANCE_UPDATE: 'attendance.update',
  ATTENDANCE_MANAGE: 'attendance.manage',

  ASSESSMENT_READ: 'assessment.read',
  ASSESSMENT_CREATE: 'assessment.create',
  ASSESSMENT_UPDATE: 'assessment.update',
  ASSESSMENT_MANAGE: 'assessment.manage',

  MARKS_READ: 'marks.read',
  MARKS_ENTER: 'marks.enter',
  MARKS_SUBMIT: 'marks.submit',
  MARKS_VERIFY: 'marks.verify',
  MARKS_PUBLISH: 'marks.publish',

  EXAM_READ: 'exam.read',
  EXAM_CREATE: 'exam.create',
  EXAM_UPDATE: 'exam.update',
  EXAM_MANAGE: 'exam.manage',

  RESULTS_READ: 'results.read',
  RESULTS_VERIFY: 'results.verify',
  RESULTS_PUBLISH: 'results.publish',

  TRANSCRIPT_READ: 'transcript.read',
  TRANSCRIPT_GENERATE: 'transcript.generate',
  TRANSCRIPT_VERIFY: 'transcript.verify'
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

const academicAdmin: Permission[] = [
  PERMISSIONS.FACULTY_READ, PERMISSIONS.FACULTY_CREATE, PERMISSIONS.FACULTY_UPDATE,
  PERMISSIONS.DEPARTMENT_READ, PERMISSIONS.DEPARTMENT_CREATE, PERMISSIONS.DEPARTMENT_UPDATE,
  PERMISSIONS.PROGRAM_READ, PERMISSIONS.PROGRAM_CREATE, PERMISSIONS.PROGRAM_UPDATE,
  PERMISSIONS.COURSE_READ, PERMISSIONS.COURSE_CREATE, PERMISSIONS.COURSE_UPDATE,
  PERMISSIONS.STUDENTS_READ, PERMISSIONS.STUDENTS_CREATE, PERMISSIONS.STUDENTS_UPDATE, PERMISSIONS.STUDENTS_MANAGE,
  PERMISSIONS.LECTURERS_READ, PERMISSIONS.LECTURERS_CREATE, PERMISSIONS.LECTURERS_UPDATE, PERMISSIONS.LECTURERS_MANAGE,
  PERMISSIONS.ACADEMIC_YEAR_MANAGE, PERMISSIONS.SEMESTER_MANAGE, PERMISSIONS.COURSE_SECTION_MANAGE,
  PERMISSIONS.REGISTRATION_READ, PERMISSIONS.REGISTRATION_APPROVE, PERMISSIONS.REGISTRATION_REJECT,
  PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_CREATE, PERMISSIONS.ATTENDANCE_UPDATE, PERMISSIONS.ATTENDANCE_MANAGE,
  PERMISSIONS.ASSESSMENT_READ, PERMISSIONS.ASSESSMENT_CREATE, PERMISSIONS.ASSESSMENT_UPDATE, PERMISSIONS.ASSESSMENT_MANAGE,
  PERMISSIONS.MARKS_READ, PERMISSIONS.MARKS_ENTER, PERMISSIONS.MARKS_SUBMIT, PERMISSIONS.MARKS_VERIFY, PERMISSIONS.MARKS_PUBLISH,
  PERMISSIONS.EXAM_READ, PERMISSIONS.EXAM_CREATE, PERMISSIONS.EXAM_UPDATE, PERMISSIONS.EXAM_MANAGE,
  PERMISSIONS.RESULTS_READ, PERMISSIONS.RESULTS_VERIFY, PERMISSIONS.RESULTS_PUBLISH,
  PERMISSIONS.TRANSCRIPT_READ, PERMISSIONS.TRANSCRIPT_GENERATE, PERMISSIONS.TRANSCRIPT_VERIFY
];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [...academicAdmin, PERMISSIONS.USERS_READ, PERMISSIONS.USERS_CREATE, PERMISSIONS.USERS_UPDATE, PERMISSIONS.AUDIT_READ],
  HOD: [
    PERMISSIONS.DEPARTMENT_READ, PERMISSIONS.PROGRAM_READ, PERMISSIONS.COURSE_READ,
    PERMISSIONS.STUDENTS_READ, PERMISSIONS.STUDENTS_UPDATE, PERMISSIONS.LECTURERS_READ,
    PERMISSIONS.REGISTRATION_READ, PERMISSIONS.REGISTRATION_APPROVE, PERMISSIONS.REGISTRATION_REJECT,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ASSESSMENT_READ,
    PERMISSIONS.MARKS_READ, PERMISSIONS.MARKS_VERIFY,
    PERMISSIONS.EXAM_READ, PERMISSIONS.EXAM_CREATE, PERMISSIONS.EXAM_UPDATE, PERMISSIONS.EXAM_MANAGE,
    PERMISSIONS.RESULTS_READ, PERMISSIONS.RESULTS_VERIFY,
    PERMISSIONS.TRANSCRIPT_READ
  ],
  LECTURER: [
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_CREATE, PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.ASSESSMENT_READ, PERMISSIONS.ASSESSMENT_CREATE, PERMISSIONS.ASSESSMENT_UPDATE,
    PERMISSIONS.MARKS_READ, PERMISSIONS.MARKS_ENTER, PERMISSIONS.MARKS_SUBMIT,
    PERMISSIONS.EXAM_READ,
    PERMISSIONS.RESULTS_READ
  ],
  FINANCE: [],
  STUDENT: [
    PERMISSIONS.REGISTRATION_CREATE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ASSESSMENT_READ,
    PERMISSIONS.MARKS_READ,
    PERMISSIONS.EXAM_READ,
    PERMISSIONS.RESULTS_READ,
    PERMISSIONS.TRANSCRIPT_READ
  ]
};
