import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod'; import { zodResolver } from '@hookform/resolvers/zod';
import { Button, Card, Input, Logo } from '../components/ui'; import { authService } from '../services/auth.service';
export function ForgotPasswordPage() { const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<{ email: string }>({ resolver: zodResolver(z.object({ email: z.string().email('Enter a valid email') })) }); const [done, setDone] = useSearchParams(); const submit = async ({ email }: { email: string }) => { await authService.forgotPassword(email); setDone({ sent: 'true' }); }; return <Centered><h1>Reset your password</h1><p>Enter your university email and we’ll send reset instructions.</p>{done.get('sent') ? <p className="mt-6 rounded-xl bg-green-50 p-4 text-sm text-green-700">If the account exists, reset instructions have been sent.</p> : <form className="mt-6 space-y-4" onSubmit={handleSubmit(submit)}><Input label="Email address" type="email" error={errors.email?.message} {...register('email')}/><Button className="w-full" loading={isSubmitting}>Send instructions</Button></form>}</Centered>; }
export function ResetPasswordPage() { const [params] = useSearchParams(); const nav = useNavigate(); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<{ password: string }>({ resolver: zodResolver(z.object({ password: z.string().min(8, 'Use at least 8 characters') })) }); const submit = async ({ password }: { password: string }) => { await authService.resetPassword(params.get('token') ?? '', password); nav('/login'); }; return <Centered><h1>Choose a new password</h1><p>Set a strong password for your HURU account.</p><form className="mt-6 space-y-4" onSubmit={handleSubmit(submit)}><Input label="New password" type="password" error={errors.password?.message} {...register('password')}/><Button className="w-full" loading={isSubmitting}>Reset password</Button></form></Centered>; }
export function SettingsPage() { return <><p className="text-sm text-muted">Preferences</p><h1 className="text-2xl font-extrabold text-ink dark:text-white">Settings</h1><Card className="mt-6 max-w-xl p-6"><h2 className="font-bold text-ink dark:text-white">Platform preferences</h2><p className="mt-2 text-sm leading-6 text-muted">Your theme preference is stored locally and is applied automatically whenever you return to HURU.</p></Card></>; }
export function ForbiddenPage() { return <Centered><h1>Access restricted</h1><p>Your account does not have permission to view this page.</p><Link to="/dashboard"><Button className="mt-6">Return to dashboard</Button></Link></Centered>; }
export function NotFoundPage() { return <Centered><h1>Page not found</h1><p>The page you’re looking for is unavailable or may have moved.</p><Link to="/"><Button className="mt-6">Go home</Button></Link></Centered>; }
function Centered({ children }: { children: React.ReactNode }) { return <main className="grid min-h-screen place-items-center p-5"><Card className="w-full max-w-md p-7"><Link to="/"><Logo/></Link><div className="mt-8 [&>h1]:text-2xl [&>h1]:font-extrabold [&>h1]:text-ink [&>h1]:dark:text-white [&>p]:mt-2 [&>p]:text-sm [&>p]:leading-6 [&>p]:text-muted">{children}</div></Card></main>; }
