import { AlertCircle, ChevronLeft, ChevronRight, LoaderCircle, Moon, Sun } from 'lucide-react';
import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode } from 'react';
import { useTheme } from '../context/ThemeContext';

export const Logo = ({ light = false }: { light?: boolean }) => <div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${light ? 'bg-white text-university-500' : 'bg-university-500 text-white'} text-sm font-extrabold shadow-sm`}>HU</span><span><strong className={`block text-sm tracking-tight ${light ? 'text-white' : 'text-ink dark:text-white'}`}>HURU</strong><small className={`block text-[10px] font-medium ${light ? 'text-blue-100' : 'text-muted dark:text-slate-400'}`}>Hormuud University</small></span></div>;
export const ThemeSwitch = () => { const { theme, toggleTheme } = useTheme(); return <button onClick={toggleTheme} aria-label="Toggle colour theme" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-100 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800">{theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button>; };
export const Button = ({ children, className = '', loading, variant = 'primary', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { loading?: boolean; variant?: 'primary' | 'secondary' | 'danger' }) => <button {...props} disabled={loading || props.disabled} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-60 ${variant === 'primary' ? 'bg-university-500 text-white hover:bg-university-600' : variant === 'danger' ? 'bg-red-600 text-white hover:bg-red-700' : 'border border-slate-300 bg-white text-ink hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-white'} ${className}`}>{loading && <LoaderCircle size={17} className="animate-spin" />}{children}</button>;
export const Input = ({ label, error, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) => <label className="block text-sm font-medium text-ink dark:text-slate-200">{label}<input {...props} className="field" />{error && <span className="mt-1 flex items-center gap-1 text-xs text-red-600"><AlertCircle size={13}/>{error}</span>}</label>;
export const Card = ({ children, className = '' }: { children: ReactNode; className?: string }) => <section className={`surface ${className}`}>{children}</section>;
export const Badge = ({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'success' | 'warning' | 'neutral' | 'danger' }) => <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tone === 'success' ? 'bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-300' : tone === 'warning' ? 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300' : tone === 'danger' ? 'bg-red-100 text-red-700' : 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300'}`}>{children}</span>;
export const Skeleton = ({ className = '' }: { className?: string }) => <div className={`animate-pulse rounded-lg bg-slate-200 dark:bg-slate-800 ${className}`} />;
export const EmptyState = ({ title, text }: { title: string; text: string }) => <div className="py-14 text-center"><p className="font-semibold text-ink dark:text-white">{title}</p><p className="mt-1 text-sm text-muted">{text}</p></div>;
export const Pagination = ({ page, pages, onPage }: { page: number; pages: number; onPage: (n: number) => void }) => <div className="flex items-center justify-between border-t border-slate-200 px-5 py-3 text-sm dark:border-slate-800"><span className="text-muted">Page {page} of {Math.max(1, pages)}</span><div className="flex gap-2"><Button variant="secondary" className="!px-3 !py-2" aria-label="Previous page" disabled={page <= 1} onClick={() => onPage(page - 1)}><ChevronLeft size={16}/></Button><Button variant="secondary" className="!px-3 !py-2" aria-label="Next page" disabled={page >= pages} onClick={() => onPage(page + 1)}><ChevronRight size={16}/></Button></div></div>;
